//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public Office()
        {
            this.Vists = new HashSet<Vist>();
        }
    
        public int id { get; set; }
        public string OfficeName { get; set; }
        public string PhoneNum { get; set; }
        public string FaxNum { get; set; }
        public string County { get; set; }
        public string AddressL1 { get; set; }
        public string AddressL2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int zipcode { get; set; }
        public Nullable<int> zip4 { get; set; }
    
        public virtual ICollection<Vist> Vists { get; set; }
    }
}
