//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramsViewed
    {
        public int VisitID { get; set; }
        public int ProgramID { get; set; }
    
        public virtual Program Program { get; set; }
        public virtual Vist Vist { get; set; }
    }
}
